// Generated by firmware/tools/generate_clips.py — do not edit.
// Voice: hi-IN-SwaraNeural, 16000 Hz, 8-bit unsigned mono PCM.
#pragma once
#include <stdint.h>

constexpr uint32_t CLIP_SAMPLE_RATE = 16000;

enum ClipId : uint16_t {
  CLIP_N1,  // एक
  CLIP_N2,  // दो
  CLIP_N3,  // तीन
  CLIP_N4,  // चार
  CLIP_N5,  // पाँच
  CLIP_N6,  // छह
  CLIP_N7,  // सात
  CLIP_N8,  // आठ
  CLIP_N9,  // नौ
  CLIP_N10,  // दस
  CLIP_N11,  // ग्यारह
  CLIP_N12,  // बारह
  CLIP_N13,  // तेरह
  CLIP_N14,  // चौदह
  CLIP_N15,  // पंद्रह
  CLIP_N16,  // सोलह
  CLIP_N17,  // सत्रह
  CLIP_N18,  // अठारह
  CLIP_N19,  // उन्नीस
  CLIP_N20,  // बीस
  CLIP_N21,  // इक्कीस
  CLIP_N22,  // बाईस
  CLIP_N23,  // तेईस
  CLIP_N24,  // चौबीस
  CLIP_N25,  // पच्चीस
  CLIP_N26,  // छब्बीस
  CLIP_N27,  // सत्ताईस
  CLIP_N28,  // अट्ठाईस
  CLIP_N29,  // उनतीस
  CLIP_N30,  // तीस
  CLIP_N31,  // इकतीस
  CLIP_N32,  // बत्तीस
  CLIP_N33,  // तैंतीस
  CLIP_N34,  // चौंतीस
  CLIP_N35,  // पैंतीस
  CLIP_N36,  // छत्तीस
  CLIP_N37,  // सैंतीस
  CLIP_N38,  // अड़तीस
  CLIP_N39,  // उनतालीस
  CLIP_N40,  // चालीस
  CLIP_N41,  // इकतालीस
  CLIP_N42,  // बयालीस
  CLIP_N43,  // तैंतालीस
  CLIP_N44,  // चवालीस
  CLIP_N45,  // पैंतालीस
  CLIP_N46,  // छियालीस
  CLIP_N47,  // सैंतालीस
  CLIP_N48,  // अड़तालीस
  CLIP_N49,  // उनचास
  CLIP_N50,  // पचास
  CLIP_N51,  // इक्यावन
  CLIP_N52,  // बावन
  CLIP_N53,  // तिरपन
  CLIP_N54,  // चौवन
  CLIP_N55,  // पचपन
  CLIP_N56,  // छप्पन
  CLIP_N57,  // सत्तावन
  CLIP_N58,  // अट्ठावन
  CLIP_N59,  // उनसठ
  CLIP_N60,  // साठ
  CLIP_N61,  // इकसठ
  CLIP_N62,  // बासठ
  CLIP_N63,  // तिरसठ
  CLIP_N64,  // चौंसठ
  CLIP_N65,  // पैंसठ
  CLIP_N66,  // छियासठ
  CLIP_N67,  // सड़सठ
  CLIP_N68,  // अड़सठ
  CLIP_N69,  // उनहत्तर
  CLIP_N70,  // सत्तर
  CLIP_N71,  // इकहत्तर
  CLIP_N72,  // बहत्तर
  CLIP_N73,  // तिहत्तर
  CLIP_N74,  // चौहत्तर
  CLIP_N75,  // पचहत्तर
  CLIP_N76,  // छिहत्तर
  CLIP_N77,  // सतहत्तर
  CLIP_N78,  // अठहत्तर
  CLIP_N79,  // उन्यासी
  CLIP_N80,  // अस्सी
  CLIP_N81,  // इक्यासी
  CLIP_N82,  // बयासी
  CLIP_N83,  // तिरासी
  CLIP_N84,  // चौरासी
  CLIP_N85,  // पचासी
  CLIP_N86,  // छियासी
  CLIP_N87,  // सत्तासी
  CLIP_N88,  // अट्ठासी
  CLIP_N89,  // नवासी
  CLIP_N90,  // नब्बे
  CLIP_N91,  // इक्यानबे
  CLIP_N92,  // बानबे
  CLIP_N93,  // तिरानबे
  CLIP_N94,  // चौरानबे
  CLIP_N95,  // पंचानबे
  CLIP_N96,  // छियानबे
  CLIP_N97,  // सत्तानबे
  CLIP_N98,  // अट्ठानबे
  CLIP_N99,  // निन्यानबे
  CLIP_SHUNYA,  // शून्य
  CLIP_SAU,  // सौ
  CLIP_HAZAAR,  // हज़ार
  CLIP_LAKH,  // लाख
  CLIP_CRORE,  // करोड़
  CLIP_RUPAYE,  // रुपये
  CLIP_RUPAYA,  // रुपया
  CLIP_PAISE,  // पैसे
  CLIP_AUR,  // और
  CLIP_DOT,  // डॉट
  CLIP_PREFIX_MERCHANT,  // भुगतान प्राप्त हुआ
  CLIP_PREFIX_GPAY,  // गूगल पे पर भुगतान प्राप्त हुआ
  CLIP_PREFIX_BANK,  // बैंक खाते में राशि जमा हुई
  CLIP_TEST_OK,  // स्पीकर ठीक से काम कर रहा है
  CLIP_PAIRED,  // फ़ोन सफलतापूर्वक जुड़ गया
  CLIP_WIFI_OK,  // वाईफ़ाई से जुड़ गया
  CLIP_WIFI_FAIL,  // वाईफ़ाई से नहीं जुड़ पाया
  CLIP_SETUP_MODE,  // सेटअप मोड चालू है। फ़ोन से स्पीकर सेटअप वाईफ़ाई से जुड़ें
  CLIP_RESET,  // स्पीकर रीसेट हो गया
  CLIP_IP_ADDRESS,  // आई पी पता
  CLIP_PIN,  // पिन
  CLIP_COUNT
};

struct ClipData {
  const uint8_t* data;
  uint32_t length;
};

extern const ClipData CLIP_TABLE[CLIP_COUNT];
