"""Generates the Hindi voice clips and bakes them into the firmware.

Writes firmware/universal-speaker/clips.h and clips.cpp: 8-bit unsigned mono
PCM at 16 kHz, the format the ESP32 internal DAC plays directly. Clips live in
flash, so the firmware is a single upload (no filesystem step).

Setup (once):  pip install edge-tts imageio-ffmpeg
Run:           python firmware/tools/generate_clips.py [--voice hi-IN-MadhurNeural]
"""

import argparse
import asyncio
import subprocess
import sys
import tempfile
from array import array
from pathlib import Path

import edge_tts
import imageio_ffmpeg

SAMPLE_RATE = 16000
OUT_DIR = Path(__file__).resolve().parent.parent / "universal-speaker"

# 1–99 in Hindi are all irregular, so each gets its own clip. Order matters:
# the firmware addresses them as CLIP_N1 + n - 1.
NUMBERS = (
    "एक दो तीन चार पाँच छह सात आठ नौ दस "
    "ग्यारह बारह तेरह चौदह पंद्रह सोलह सत्रह अठारह उन्नीस बीस "
    "इक्कीस बाईस तेईस चौबीस पच्चीस छब्बीस सत्ताईस अट्ठाईस उनतीस तीस "
    "इकतीस बत्तीस तैंतीस चौंतीस पैंतीस छत्तीस सैंतीस अड़तीस उनतालीस चालीस "
    "इकतालीस बयालीस तैंतालीस चवालीस पैंतालीस छियालीस सैंतालीस अड़तालीस उनचास पचास "
    "इक्यावन बावन तिरपन चौवन पचपन छप्पन सत्तावन अट्ठावन उनसठ साठ "
    "इकसठ बासठ तिरसठ चौंसठ पैंसठ छियासठ सड़सठ अड़सठ उनहत्तर सत्तर "
    "इकहत्तर बहत्तर तिहत्तर चौहत्तर पचहत्तर छिहत्तर सतहत्तर अठहत्तर उन्यासी अस्सी "
    "इक्यासी बयासी तिरासी चौरासी पचासी छियासी सत्तासी अट्ठासी नवासी नब्बे "
    "इक्यानबे बानबे तिरानबे चौरानबे पंचानबे छियानबे सत्तानबे अट्ठानबे निन्यानबे"
).split()
assert len(NUMBERS) == 99, len(NUMBERS)

# (enum name, text, trailing silence in ms)
CLIPS = [(f"N{i}", word, 0) for i, word in enumerate(NUMBERS, start=1)] + [
    ("SHUNYA", "शून्य", 0),
    ("SAU", "सौ", 0),
    ("HAZAAR", "हज़ार", 0),
    ("LAKH", "लाख", 0),
    ("CRORE", "करोड़", 0),
    ("RUPAYE", "रुपये", 0),
    ("RUPAYA", "रुपया", 0),
    ("PAISE", "पैसे", 0),
    ("AUR", "और", 0),
    ("DOT", "डॉट", 0),
    ("PREFIX_MERCHANT", "भुगतान प्राप्त हुआ", 250),
    ("PREFIX_GPAY", "गूगल पे पर भुगतान प्राप्त हुआ", 250),
    ("PREFIX_BANK", "बैंक खाते में राशि जमा हुई", 250),
    ("TEST_OK", "स्पीकर ठीक से काम कर रहा है", 0),
    ("PAIRED", "फ़ोन सफलतापूर्वक जुड़ गया", 0),
    ("WIFI_OK", "वाईफ़ाई से जुड़ गया", 0),
    ("WIFI_FAIL", "वाईफ़ाई से नहीं जुड़ पाया", 0),
    ("SETUP_MODE", "सेटअप मोड चालू है। फ़ोन से स्पीकर सेटअप वाईफ़ाई से जुड़ें", 0),
    ("RESET", "स्पीकर रीसेट हो गया", 0),
    ("IP_ADDRESS", "आई पी पता", 250),
    ("PIN", "पिन", 250),
]


async def synthesize(text: str, voice: str, rate: str, mp3_path: Path) -> None:
    # The edge-tts service occasionally drops a request ("No audio received").
    for attempt in range(4):
        try:
            await edge_tts.Communicate(text, voice, rate=rate).save(str(mp3_path))
            return
        except Exception:
            if attempt == 3:
                raise
            await asyncio.sleep(2 * (attempt + 1))


def mp3_to_pcm_u8(mp3_path: Path, trailing_ms: int) -> bytes:
    """Decode, trim leading/trailing silence, peak-normalise, convert to u8."""
    trim = "silenceremove=start_periods=1:start_threshold=-45dB"
    raw = subprocess.run(
        [
            imageio_ffmpeg.get_ffmpeg_exe(), "-v", "error", "-i", str(mp3_path),
            "-af", f"{trim},areverse,{trim},areverse",
            "-ac", "1", "-ar", str(SAMPLE_RATE), "-f", "s16le", "-",
        ],
        check=True,
        capture_output=True,
    ).stdout
    samples = array("h", raw)
    peak = max((abs(s) for s in samples), default=0) or 1
    gain = 0.95 * 127 / peak  # 16-bit -> ±127 around the 128 midpoint
    pcm = bytes(max(0, min(255, 128 + round(s * gain))) for s in samples)
    return pcm + bytes([128]) * (SAMPLE_RATE * trailing_ms // 1000)


def write_sources(clips: list[tuple[str, str, bytes]], voice: str) -> None:
    header = [
        "// Generated by firmware/tools/generate_clips.py — do not edit.",
        f"// Voice: {voice}, {SAMPLE_RATE} Hz, 8-bit unsigned mono PCM.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"constexpr uint32_t CLIP_SAMPLE_RATE = {SAMPLE_RATE};",
        "",
        "enum ClipId : uint16_t {",
        *[f"  CLIP_{name},  // {text}" for name, text, _ in clips],
        "  CLIP_COUNT",
        "};",
        "",
        "struct ClipData {",
        "  const uint8_t* data;",
        "  uint32_t length;",
        "};",
        "",
        "extern const ClipData CLIP_TABLE[CLIP_COUNT];",
        "",
    ]
    body = ['// Generated by firmware/tools/generate_clips.py — do not edit.', '#include "clips.h"', ""]
    for name, text, pcm in clips:
        body.append(f"// {text}")
        body.append(f"static const uint8_t DATA_{name}[{len(pcm)}] = {{")
        for i in range(0, len(pcm), 32):
            body.append("  " + ",".join(str(b) for b in pcm[i : i + 32]) + ",")
        body.append("};")
    body.append("")
    body.append("const ClipData CLIP_TABLE[CLIP_COUNT] = {")
    body += [f"  {{DATA_{name}, sizeof(DATA_{name})}}," for name, _, _ in clips]
    body.append("};")
    body.append("")

    (OUT_DIR / "clips.h").write_text("\n".join(header), encoding="utf-8")
    (OUT_DIR / "clips.cpp").write_text("\n".join(body), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--voice", default="hi-IN-SwaraNeural", help="or hi-IN-MadhurNeural (male)")
    parser.add_argument("--rate", default="+5%", help="speaking rate, e.g. +10%%")
    args = parser.parse_args()

    results = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, text, trailing_ms in CLIPS:
            mp3 = Path(tmp) / f"{name}.mp3"
            asyncio.run(synthesize(text, args.voice, args.rate, mp3))
            pcm = mp3_to_pcm_u8(mp3, trailing_ms)
            results.append((name, text, pcm))
            print(f"{name:16} {len(pcm) / SAMPLE_RATE:5.2f}s  {text}")

    write_sources(results, args.voice)
    total = sum(len(p) for _, _, p in results)
    print(f"\n{len(results)} clips, {total / 1024:.0f} KB, {total / SAMPLE_RATE:.0f}s of audio -> {OUT_DIR}")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    main()
